
  
services:
  # ---------------------------------------------------------
  # Usage:
  # docker compose up --build -d
  # ---------------------------------------------------------

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    ports:
      - 9011:9011
    use_api_socket: true
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      - --servers=mcp-talk-to-somebody,mcp-roll-dices

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./catalog.yaml:/mcp/catalog.yaml

    depends_on:
      mcp-talk-to-somebody:
        condition: service_healthy
      mcp-roll-dices:
        condition: service_healthy
  
  mcp-talk-to-somebody:
    build:
      context: mcp-server-talk-to-somebody
      dockerfile: Dockerfile      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-roll-dices:
    build:
      context: mcp-server-roll-dices
      dockerfile: Dockerfile      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

