# ---------------------------------------------------------
# Usage:
# docker compose up --build -d
# ---------------------------------------------------------
services:
  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    ports:
      - 9011:9011
    use_api_socket: true
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      - --servers=mcp-talk-to-somebody,mcp-roll-dices
    configs:
      - source: catalog.yaml
        target:
          /mcp/catalog.yaml
    depends_on:
      mcp-talk-to-somebody:
        condition: service_healthy
      mcp-roll-dices:
        condition: service_healthy
  zephyr:
    build:
      context: zephyr
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      MCP_HOST: http://mcp-gateway:9011/mcp
      DUNGEON_MASTER_NAME: Zephyr
      DUNGEON_MASTER_SYSTEM_INSTRUCTIONS: |
        You are a friendly and helpful Dungeon Master for a Dungeons & Dragons game.
        You will guide the player through a fantasy adventure, describing scenes, challenges, and characters.
        You will use tools to manage the game state, such as creating a player, starting a quest, and rolling dice.
        You will use a conversational and immersive style, making the player feel like they are part of the adventure.
        You will avoid breaking character and stay in the role of the Dungeon Master at all times.
        You will end each response with a question or prompt to encourage the player to take action.
        Use all the provided data to make the adventure, the rooms description... engaging and coherent.
        The response format is done in markdown, well structured with titles, subtitles, bullet points...

    models:
      zephyr-model:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: DUNGEON_MASTER_MODEL
    depends_on:
      - mcp-gateway
  mcp-talk-to-somebody:
    build:
      context: mcp-server-talk-to-somebody
      dockerfile: Dockerfile      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-roll-dices:
    build:
      context: mcp-server-roll-dices
      dockerfile: Dockerfile      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

models:
  zephyr-model:
    model: hf.co/menlo/jan-nano-gguf:q4_k_m
    runtime_flags:
      - "--temp"                # Temperature
      - "0.7"

configs:
  catalog.yaml:
    content: |
      registry:
        mcp-talk-to-somebody:
          remote:
            url: "http://mcp-talk-to-somebody:9090/mcp"
            transport_type: http

        mcp-roll-dices:
          remote:
            url: "http://mcp-roll-dices:9090/mcp"
            transport_type: http
