services:
  sorcerer-agent:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.25.1-alpine
        WORKDIR /app
        COPY . .

        RUN go mod tidy
        ENTRYPOINT ["go", "run", "main.go"]
    environment:
      - SORCERER_SYSTEM_INSTRUCTIONS_PATH=/app/data/sorcerer_system_instructions.md
      - SORCERER_CONTEXT_PATH=/app/data/sorcerer_background_and_personality.md
      - SORCERER_NAME=Elara
      - VECTOR_STORES_PATH=/app/data
    models:
      sorcerer:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: ELARA_MODEL
      embedding:
        model_var: EMBEDDING_URL

models:
  sorcerer:
    model: ai/qwen2.5:1.5B-F16
    context_size: 4096
    runtime_flags:
        - "--temp"                # Temperature
        - "0.8"
        - "--verbose"
        - "--verbose-prompt"
  embedding:
    model: ai/mxbai-embed-large