services:
  mcp-talk-to-somebody:
    build:
      context: .
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    ports:
      - 9011:9011
    use_api_socket: true
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      - --servers=mcp-talk-to-somebody
    configs:
      - source: catalog.yaml
        target: /mcp/catalog.yaml

    depends_on:
      mcp-talk-to-somebody:
        condition: service_healthy

  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    command: ["--config", "/app/mcp.json"]
    ports:
      - 6274:6274
      - 6277:6277
    environment:
      HOST: 0.0.0.0
      ALLOWED_ORIGINS: "http://0.0.0.0:6274,http://localhost:6274"
      MCP_AUTO_OPEN_ENABLED: false
    depends_on:
      - mcp-gateway

configs:
  catalog.yaml:
    content: |
      registry:
        mcp-talk-to-somebody:
          remote:
            url: "http://mcp-talk-to-somebody:9090/mcp"
            transport_type: http